import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]
[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

opacity = 0.7
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 16
